#!/bin/bash

echo "[git hook] executing maven verify phase before commit."

# stash any unstaged changes
git stash -q --keep-index

# run verify
cd backend
./mvnw verify

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

# return the exit code
exit $RESULT